name: Develop Testing - Flutter

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [develop]
  workflow_dispatch:
jobs:
  build:
    name: Build, Analyze & Test
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.1
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test